#------------------------------------------------------------------------------
# written by: mcdaniel
# date: june-2022
#
# usage: Use tutor to enable the Open edX Discussion service plugin
#        Called from tutor_deploy.yml
#
# FIX NOTE: move to Github Actions marketplace
#------------------------------------------------------------------------------
name: Open edX Tutor k8s enable Discussion Forum plugin
description: Github Action to install and enable the Tutor plugin - Open edX Discussion Forum service
branding:
  icon: 'cloud'
  color: 'orange'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Configure Discussion Forum
      run:  |-
        pip install tutor-forum
        tutor plugins enable forum
        tutor config save
      shell: bash
