#------------------------------------------------------------------------------
# written by: mcdaniel
# date: june-2022
#
# usage: Use tutor to enable the Open edX Discussion service plugin
#        Called from tutor_deploy.yml
#
# FIX NOTE: move to Github Actions marketplace
#------------------------------------------------------------------------------
name: Open edX Tutor k8s enable Discussion Forum plugin
description: Github Action to install and enable the Tutor plugin - Open edX Discussion Forum service
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  tutor-forum-version:
    description: 'The version of tutor-forum to install'
    required: false
    default: latest
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2

    - name: Configure Discussion Forum
      run:  |-
        pip install tutor-forum${{ inputs.tutor-forum-version != 'latest' && format('=={0}', inputs.tutor-forum-version) || '' }}
        tutor plugins enable forum
        tutor config save
      shell: bash
